#!/bin/bash -ue
# Christian Bryn <chr.bryn@gmail.com> 2014-2017
# by courtesy of http://someonewhocares.org/hosts/zero/
# fetches remote zerohosts file and safely appends to /etc/hosts
# requires sudo privileges for some actions
#
# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# <chr.bryn@gmail.com> wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return.
# Christian Bryn
# ----------------------------------------------------------------------------
#

## config
remote_hosts_file="http://someonewhocares.org/hosts/hosts"
remote_hosts_zero_file="http://someonewhocares.org/hosts/zero/"
hosts_file="/etc/hosts"
zerohosts_tmp_file="$(mktemp)"

## flags
quiet="false"
route_method="local"
update="false"

# fancy terminal stuff
if [ -t 1 ]; then
    exec 3>&2 2>/dev/null
    b=$( tput bold ) || true
    red=$( tput setf 4 ) || true
    green=$( tput setf 2 ) || true
    yellow=$( tput setf 6 ) || true
    t_reset=$( tput sgr0 ) || true
    exec 2>&3; exec 3>&-
fi

## functions
function print_usage {
  cat <<EOF
Safely append zerohosts to /etc/hosts
This script will prompt for a sudo password.

Usage: ${0} [-hdq]
  -h    This helpful text
  -d    Delete entries previosly added.
  -q    Quiet - only print errors.
  -z    Route to 0.0.0.0 (default: 127.0.0.1)

Examples:
  ${0}
  ${0} -z
  # run from cron - requires root privilegies / passwordless sudo
  ${0} -q
EOF
}

function p_err {
    # print errors
    # params: <string>
    local string="${@}"
    printf "${b:-}${red:-}>>${t_reset:-} %s\n" "${string}"
}

function p_info {
    # print info
    # params: <string>
    local string="${@}"
    [[ "${quiet}" == "false" ]] && printf "${b:-}${yellow:-}>>${t_reset:-} %s\n" "${string}"
}

function delete_entries_found {
  if ( egrep -q "^### ZEROHOSTS BEGIN ###$" "${hosts_file}" )
  then
    #p_info "ZERODATA BEGIN marker found."
    if ( ! egrep -q "^### ZEROHOSTS END ###$" "${hosts_file}" )
    then
      p_err "You have a 'ZEROHOSTS BEGIN' marker in your hosts file, but no 'ZEROHOSTS END' marker - bogus, man! Please fix to continue."
      exit 1
    fi
    p_info "Deleting old ZEROHOSTS entries. Hope you didn't manually change them."
    p_info "...need elevated privileges to do this - may prompt for sudo password"
    sudo sed -i '/^### ZEROHOSTS BEGIN ###$/,/^### ZEROHOSTS END ###$/ d' "${hosts_file}"
    p_info "OK, hopefully I removed the old ones..."
  fi
}

while getopts hdqz o
do
  case $o in
    h)
      print_usage ; exit ;;
    a)
      update="true" ;;
    d)
      delete_entries_found ; exit ;;
    q)
      update="true"
      quiet="true" ;;
    z)
      update="true"
      route_method="zero" ;;
  esac
done
shift $(($OPTIND-1))

[[ "${update}" != "true" ]] && { echo "No update/delete action specified!"; print_usage; exit; }

trap 'rm "${zerohosts_tmp_file}"' EXIT

p_info "Fetching remote file..."
case $route_method in
  "hosts")
    curl -s "${remote_hosts_file}" > "${zerohosts_tmp_file}" ;;
  "zero")
    curl -s "${remote_hosts_zero_file}" > "${zerohosts_tmp_file}" ;;
esac

p_info "Backing up existing hosts file to /tmp/"
p_info "You should verify the results after having run this script."
cp /etc/hosts /tmp/hosts.$( date "+%s" )

delete_entries_found

p_info "Adding new entries!"

echo "### ZEROHOSTS BEGIN ###" | sudo tee -a "${hosts_file}" >/dev/null
cat "${zerohosts_tmp_file}" | sudo tee -a "${hosts_file}" >/dev/null
echo "### ZEROHOSTS END ###" | sudo tee -a "${hosts_file}" >/dev/null

p_info "Allright. I hope this went well. Happy surfing!"
