#!/bin/bash -ue
# Christian Bryn <chr.bryn@gmail.com> 2014
# by courtesy of http://someonewhocares.org/hosts/zero/
#
# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# <chr.bryn@gmail.com> wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return Poul-Henning Kamp
# ----------------------------------------------------------------------------
#


remote_hosts_file="http://someonewhocares.org/hosts/hosts"
hosts_file="/etc/hosts"
zerohosts_tmp_file="/tmp/zerohosts.tmp"

echo "Fetching remote file..."
curl -s "${remote_hosts_file}" > "${zerohosts_tmp_file}"

echo "Backing up existing hosts file to /tmp/ if needed."
echo "You should verify the results after having run this script."
cp /etc/hosts /tmp/hosts.$( date "+%s" )

if ( egrep -q "^### ZEROHOSTS BEGIN ###$" "${hosts_file}" )
then
  echo "ZERODATA BEGIN marker found."
  if ( ! egrep -q "^### ZEROHOSTS END ###$" "${hosts_file}" )
  then
    echo "You have a 'ZEROHOSTS BEGIN' marker in your hosts file, but no 'ZEROHOSTS END' marker - bogus, man! Please fix to continue."
    exit 1
  fi
  echo "Deleting old ZEROHOSTS entries. Hope you didn't manually change them."
  echo "Need elevated privileges to do this - may prompt for sudo password"
  sudo sed -i '/^### ZEROHOSTS BEGIN ###$/,/^### ZEROHOSTS END ###$/ d' "${hosts_file}"
  echo "OK, hopefully I removed the old ones..."
fi
echo "Inserting new ones!"

echo "### ZEROHOSTS BEGIN ###" | sudo tee -a "${hosts_file}" >/dev/null
cat "${zerohosts_tmp_file}" | sudo tee -a "${hosts_file}" >/dev/null
echo "### ZEROHOSTS END ###" | sudo tee -a "${hosts_file}" >/dev/null

echo "Cleaning out downloaded hostsfile..."
rm "${zerohosts_tmp_file}"
echo "Allright. I hope this went well. Happy surfing!"
